version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: "Update and install build tools"
          command: |
            sudo apt-get update
            sudo apt-get install build-essential cmake clang libc6-dev-i386
      - run:
          name: "Build"
          command: |
            cd /home/circleci/project 
            source setvars.sh
            cd ${CFS_MISSION}/build/cpu1
            make clean
            make config
            make
      - run:
         name: "Launch core-linux.bin"
            cd /home/circleci/project 
            source setvars.sh
            cd ${CFS_MISSION}/build/cpu1/exe
            sudo ./core-linux.bin PO 1


